### ISSUE TITLE
three.js externs

### ISSUE THREAD

**Issue by aiba** [jmmk/javascript-externs-generator#1]
It would be amazing if this could generate an externs file for three.js

I tried it with https://cdnjs.cloudflare.com/ajax/libs/three.js/r71/three.js but got `TypeError: Cannot read property 'order' of undefined`.

**Comment by jmmk** [comment]
Yeah, I've seen the three.js failure before (listed in the README), so thank you for opening the issue!

It happens when accessing ```eulerOrder```, defined here:
```javascript
THREE.Object3D.prototype = {

	constructor: THREE.Object3D,

	get eulerOrder () {

		THREE.warn( 'THREE.Object3D: .eulerOrder has been moved to .rotation.order.' );

		return this.rotation.order;

	},

	set eulerOrder ( value ) {

		THREE.warn( 'THREE.Object3D: .eulerOrder has been moved to .rotation.order.' );

		this.rotation.order = value;

	},
```

```rotation``` is defined using ```Object.defineProperties``` here:
```javascript
Object.defineProperties( this, {
		position: {
			enumerable: true,
			value: position
		},
		rotation: {
			enumerable: true,
			value: rotation
		},
		quaternion: {
			enumerable: true,
			value: quaternion
		},
		scale: {
			enumerable: true,
			value: scale
		}
	} );
```

I haven't really investigated beyond this, but hopefully there's an easy way to catch this.

**Comment by jmmk** [comment]
It looks like these properties (rotation, position, et al.) are only available on an instance of Object3D (`new THREE.Object3D()`).

I'm wondering if I need to instantiate all prototype functions to enumerate their properties, or if this is something that can be omitted from the extern - what will the Google Closure Compiler do here? TBD with some testing.

**Comment by timgilbert** [comment]
FWIW, the externs generator at http://www.dotnetwise.com/code/externs/ is able to consume three.js and generate externs for it, though I can't evaluate how good of a job it does (I used it to generate the externs for three.js r84).

**Comment by timgilbert** [comment]
...to expand on the previous comment a bit, [three.js r84](https://cdnjs.com/libraries/three.js/) currently throws an error from this generator which seems to be caused by three using getter syntax, as in #31.

**Comment by jmmk** [comment]
@timgilbert The reason I made this in the first place was that the dotnetwise generator wasn't very thorough and I wanted a better tool, so it's a shame it supports something I don't. 

Maybe for the more difficult Javascript files that are not supported , we can fail more gracefully (just omit those properties) and generate a partial extern. I'll try this and see how it compares to the dotnetwise output.

**Comment by jmmk** [comment]
@timgilbert @aiba 

Just added a commit that successfully generates an extern for three.js: https://github.com/jmmk/javascript-externs-generator/commit/8e27de083924fc471837216302e2d4785dfab60e

#### What was happening?
I was calling `js-keys` on the prototype object. `js-keys` uses `goog.object.forEach` which calls `obj[key]`. 

If the getter property references something like `this.property.X`, where `this.property` is `undefined`, `obj[key]` throws an error since it attempts to access the property. 

#### What's the fix?
`goog.object.getKeys` just returns the names of the keys, which is what we wanted in the first place. It won't do any property access so won't get caught by this.

**Comment by timgilbert** [comment]
Hey, that's great, thanks @jmmk!
