### ISSUE TITLE
Stuck with draft-js

### ISSUE THREAD

**Issue by abhi18av** [jmmk/javascript-externs-generator#26]
@jmmk, this is quite useful tool - thanks for the effort.

Actually, I've been trying to make the extern for Draft-js , no success so far.

I've followed the instructions on https://github.com/cljsjs/packages/wiki/Creating-Packages but the error seems to be the same everytime.

<img width="1440" alt="screen shot 2016-08-21 at 10 10 54 pm" src="https://cloud.githubusercontent.com/assets/12799326/17838480/3b533140-67ec-11e6-89ae-2670fa27b5c0.png">

And I've tried various iterations of 

`
generate-extern -f draft.js -n draft -o draft-extern.js`

`
generate-extern -f draft.js -n draft-js -o draft-extern.js`

`
generate-extern -f draft.js -n draft.js -o draft-extern.js`

And the error is this 
`Namespace 'draft' was not found. Make sure the library is loaded and the name is spelled correctly.
`

**Comment by jmmk** [comment]
It looks like Draft has dependencies on React, React-DOM, and Immutable. I was able to get it working by taking the following steps:

- go to http://michaelmclellan.me/javascript-externs-generator/
- load https://cdnjs.cloudflare.com/ajax/libs/immutable/3.8.1/immutable.js
- load https://cdnjs.cloudflare.com/ajax/libs/react/15.3.1/react.js
- load https://cdnjs.cloudflare.com/ajax/libs/react/15.3.1/react-dom.js
- load https://cdnjs.cloudflare.com/ajax/libs/draft-js/0.8.1/Draft.js
- extern `Draft`

Alternatively from the command line:

- `curl -O https://cdnjs.cloudflare.com/ajax/libs/immutable/3.8.1/immutable.js`
- `curl -O https://cdnjs.cloudflare.com/ajax/libs/react/15.3.1/react.js`
- `curl -O https://cdnjs.cloudflare.com/ajax/libs/react/15.3.1/react-dom.js`
- `curl -O https://cdnjs.cloudflare.com/ajax/libs/draft-js/0.8.1/Draft.js`
- `generate-extern -f immutable.js,react.js,react-dom.js,Draft.js -n Draft -o draft-extern.js`

**Comment by abhi18av** [comment]
Thanks @jmmk , this is wonderful!

**Comment by cmal** [comment]
@jmmk Hi, I've met the same problem when trying to extern `echarts` of https://github.com/ecomfe/zrender, whose source code is http://echarts.baidu.com/dist/echarts.min.js . 

Unfortunately, it depends on https://github.com/ecomfe/zrender ,
I've tried to `generate-extern -f zrender.js,echarts.min.js -n echarts -o echarts.ext.js` but still cannot find `zrender` generated from, probably because of `zrender` does not have `exports.zrender` in its code.

 How can I extern it? Thanks very much.

**Comment by jmmk** [comment]
@cmal I was able to do the following:

- `curl -O http://echarts.baidu.com/dist/echarts.min.js`
- `generate-extern -f echarts.min.js -n echarts -o echarts-extern.js`

and it produced an extern without any errors. Did you run into an issue with this?

**Comment by cmal** [comment]
Thank you for your help @jmmk .  I didn't get an error. But I found there is an dependency `zrender` in the `echarts-extern.js` file and the extern file does not include zrender. And I cannot use `generate-extern` to get the extern of `zrender.js`.  Shall I put the extern of `zrender` into this `echarts-extern.js` file?  I've found the previous version of cljsjs/echarts have externs of `zrender` in the extern file. https://github.com/cljsjs/packages/blob/master/echarts/resources/cljsjs/echarts/common/echarts.ext.js

I do not understand whether I should put the externs of dependencies of echarts into this extern file and how. So can you help me with some information about that? Thanks.
