### ISSUE TITLE
Not working for Stickyfill

### ISSUE THREAD

**Issue by zilti** [jmmk/javascript-externs-generator#28]
I tried to generate externs for Stickyfill (http://cdnjs.cloudflare.com/ajax/libs/stickyfill/1.1.4/stickyfill.min.js) since apparently I'm too stupid to do it on my own. Turns out that in the eyes of Google Closure, your script seems to be "too stupid" as well; I get a type error at runtime.

**Comment by jmmk** [comment]
@zilti You must use the unminified version to find the externs, so http://cdnjs.cloudflare.com/ajax/libs/stickyfill/1.1.4/stickyfill.js.

I was able to generate the following extern loading the unminified file and externing `Stickyfill`:

```javascript
/**********************************************************************
 * Extern for Stickyfill
 * Generated by http://jmmk.github.io/javascript-externs-generator
 **********************************************************************/
var Stickyfill = {
  "stickies": {},
  "add": function () {},
  "remove": function () {},
  "init": function () {},
  "rebuild": function () {},
  "pause": function () {},
  "stop": function () {},
  "kill": function () {}
};
/**********************************************************************
 * End Generated Extern for Stickyfill
/**********************************************************************/
```

**Comment by zilti** [comment]
ah, I did get these, even with minified! :) I wasn't using CLJS for quite some time, turns out I was too dumb to correctly interpret the slightly confusing runtime error... Well thanks for the help nonetheless!
