### ISSUE TITLE
cannot create extern for firebase

### ISSUE THREAD

**Issue by jorda0mega** [jmmk/javascript-externs-generator#31]
I am trying to create an extern for firebase from the following url https://www.gstatic.com/firebasejs/3.6.4/firebase.js but I keep getting the error
```TypeError: Cannot read property 'app' of undefined. Check console for stack trace.```

**Comment by jmmk** [comment]
@jorda0mega thanks for the report.

It looks like they are using [getter syntax](https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Functions/get) which I've not added support for yet.

**Comment by jmmk** [comment]
Stacktrace from the console:

![image](https://cloud.githubusercontent.com/assets/1122242/21433033/cf39df7e-c833-11e6-929f-1deeeef260d4.png)

And the offending line: `Object.defineProperty(Se.prototype,"app",{get:function(){return this.ta.app}});`

**Comment by jmmk** [comment]
@jorda0mega just added a fix, and it seems to work now. See explanation in #1
