### ISSUE TITLE
NPM package depends on itself

### ISSUE THREAD

**Issue by deepxg** [jmmk/javascript-externs-generator#34]
I assume I'm being incredibly dim and missing something here, but in `package.json` there is a dependency `"externs-generator": "^0.2.3"`. So the library seems to depend on itself, and I couldn't run `npm install` until I removed that dependency.

Is there some reason that's in there, or is it just some historical cruft left around?

**Comment by jmmk** [comment]
I'm not sure how that happened, but it definitely is not supposed to be there. I've removed it from the package.json and pushed another npm build.

Thanks for the report! Let me know if it works for you now

**Comment by kennethkalmer** [comment]
I'm still seeing this at the moment. Did you bump the version? My understanding is you can't just push files to the a version that already exists in the NPM registry. The NPM page shows the current version `0.3.2` was published two months ago.

**Comment by jmmk** [comment]
@kennethkalmer Looks like I didn't run the `publish`; it should be all set now with version 0.3.3

**Comment by kennethkalmer** [comment]
💥 

```
$ npm install externs-generator -g
/usr/local/bin/generate-extern -> /usr/local/lib/node_modules/externs-generator/bin/extern
+ externs-generator@0.3.3
added 4 packages and updated 1 package in 1.928s
```

All good now, thanks so much.
