### ISSUE TITLE
Website: unable to type anything in JS file text on Mac safari.

### ISSUE THREAD

**Issue by danielbraun** [jmmk/javascript-externs-generator#36]
1. Open https://jmmk.github.io/javascript-externs-generator/ on Mac Safari.
2. Try to interact with the textbox. It's unresponsive and stuck.

Safari Version 10.1.2 (12603.3.8)

**Comment by jmmk** [comment]
@danielbraun If I had to guess, it's some incompatibility with the UI library and Safari

Looks like it's working on Chrome, so as a workaround you can use that. I'll see if I can take a look later

**Comment by danielbraun** [comment]
Yeah, works just fine in Chrome. I’ll look into it.

**Comment by ValeryKV** [comment]
Works in FireFox either.

**Comment by jmmk** [comment]
Upgraded dependencies and it looks like everything is working now
