### ISSUE TITLE
Namespace 'jQuery.prototype.datepicker' was not found.

### ISSUE THREAD

**Issue by ValeryKV** [jmmk/javascript-externs-generator#38]
1. Load https://cdnjs.cloudflare.com/ajax/libs/jquery/3.3.1/jquery.js
2. Load https://cdnjs.cloudflare.com/ajax/libs/bootstrap-datepicker/1.7.1/js/bootstrap-datepicker.js
3. Extern! jQuery.prototype.datepicker
Error: Namespace 'jQuery.prototype.datepicker' was not found.

I also tried 'jQuery.datepicker' and 'datepicker'.

What I am doing wrong?

**Comment by jmmk** [comment]
@ValeryKV If you extern `jQuery`, it will have the `datepicker` properties nested underneath. I'm not sure 100% sure how externs should work for jQuery plugins

**Comment by ValeryKV** [comment]
It is great. Thanks.
