### ISSUE TITLE
Variable names with dashes are parsed incorrectly

### ISSUE THREAD

**Issue by AndresCuervo** [jmmk/javascript-externs-generator#40]
The generated externs for [A-Frame](https://aframe.io) ([JS loaded into generator](https://unpkg.com/aframe@0.8.2/dist/aframe-master.js)) includes instances of `x - y` for variable names that had dashes, e.g. `oculus-touch-controls`.

_screenshot from generated output in browser_:

<img width="450" alt="screen shot 2018-11-09 at 10 56 28 pm" src="https://user-images.githubusercontent.com/5826638/48298532-eccc8b00-e473-11e8-8024-af3a6979cdeb.png">

It might be helpful for changing the parser to see how I changed these into the appropriate accessor JavasScript: `['x-y']`. In Vim I executed the following regular expressions:

- `%s/\v.(\w+) - (\w+)./['\1-\2'].`
- Then followed by this to fix names with two dashes in their name (as in 'oculus-touch-controls')
  - `%s/\v\']\.- (\w+)./-\1'].`

| **before** | <img width="817" alt="oculus_error_before" src="https://user-images.githubusercontent.com/5826638/48298668-d9222400-e475-11e8-9f03-b9aa7b8367bc.png">  |
|-----|-----|
| **after** | <img width="796" alt="oculus_error_after" src="https://user-images.githubusercontent.com/5826638/48298669-db847e00-e475-11e8-8da0-6e1811863474.png"> |

I'm unfamiliar with this project but if you point me to the right code I'd be happy to add a case to fix this.

**Comment by jmmk** [comment]
@AndresCuervo I've just pushed a fix for this if you want to try again

**Comment by cwervo** [comment]
@jmmk yep, works like a charm, thanks! (note, in response to the SO question linked, the variables include Unicode characters because they're HTML attributes so `oculus-touch-controls` is meant to be used as `<thing oculus-touch-controls="x: y">`. Still, the differences in valid identifiers are rather annoying)
