### ISSUE TITLE
UX suggestion

### ISSUE THREAD

**Issue by jimrthy** [jmmk/javascript-externs-generator#5]
It took me a while to figure out that I actually needed to Load a library's files before I tried to Extern! them. I thought maybe the library I was messing with was just broken and was writing up a bug report for you about it.

Maybe you could disable the Extern! button until there's at least one file loaded? Or add something like a big green arrow pointing to the Load button, maybe with a little blurb to make it clear that the object has to be loaded first?

(Yes, looking back, it seems obvious. I was probably just frustrated at not having a "browse for local file" button).

Or maybe you could just check somewhere like extern/extract-loaded and suggest that this might be the problem if js-object came back falsey from the sandbox.

These are really minor quibbles, though. Thanks for an awesome tool!

**Comment by jmmk** [comment]
So is this the error that you saw?

![extern-error](https://cloud.githubusercontent.com/assets/1122242/15097987/b0fcd358-14fc-11e6-827d-bebfc9153637.jpg)

Would it help if that error was more specific and mentioned that a particular namespace was not found? 

For example:

* If I have not loaded jQuery yet, `sandbox.contentWindow["jQuery"]` will fail
* If I load jQuery but misspell it `jquery`, `sandbox.contentWindow["jquery"]` will fail

In both of these cases, I can display an error like "Namespace <name> was not found. Make sure you have loaded the library and that you have spelled it correctly". Also as you mentioned, the extern part could be disabled or hidden until at least one library is loaded.

**Comment by jimrthy** [comment]
That's it. Sorry for not including the actual error message.

I think changing that would be enough.

**Comment by jmmk** [comment]
I've made two changes:

#### 1. Don't show the extern section until a namespace is loaded. This way the user doesn't have any option but to first load the file.

So the initial view looks like:
<img src="https://cloud.githubusercontent.com/assets/1122242/15257218/561acdb2-1913-11e6-9497-f51184234663.png" width="75%" height="75%"/>

Upon loading a JS file:
<img src="https://cloud.githubusercontent.com/assets/1122242/15257252/7a8be1ae-1913-11e6-8c9e-1ec4eb22ab5c.png" width="75%" height="75%"/>

#### 2. Make the error more descriptive if the namespace is not found within the loaded JavaScript

Typing in a non-existent namespace:
<img src="https://cloud.githubusercontent.com/assets/1122242/15257282/948f9244-1913-11e6-8a8a-7707ca9fa995.png" width="75%" height="75%"/>

Error message:
<img src="https://cloud.githubusercontent.com/assets/1122242/15257290/9d1cff32-1913-11e6-9adb-26d9840996f1.png" width="75%" height="75%"/>


If that looks like it would solve your issues (1. Come to the page for the first time and be unsure of what to do and 2. Be unsure what happened on a missing namespace), I'll go ahead and merge this in.

**Comment by jimrthy** [comment]
Looks awesome, thank you!
