### ISSUE TITLE
Externs with syntax error

### ISSUE THREAD

**Issue by martinklepsch** [jmmk/javascript-externs-generator#6]
I generated externs for MediumButton:

https://rawgit.com/arcs-/MediumButton/master/src/MediumButton.js

Which resulted in these externs:

```js
"MediumButton": function () {}
MediumButton.prototype = {
  "getButton": function () {},
  "checkState": function () {}
};
```

Now passing this to the Closure compiler will result in the following error:
```
Parse error. Semi-colon expected "MediumButton": function () {};
                                               ^
```
Not sure what's going on there and in this case I don't mind much. Just corrected them like below but I wanted to let you know/log it in any case. Cheers 🍻 

```js
var MediumButton = function () {};
MediumButton.prototype = {
  "getButton": function () {},
  "checkState": function () {}
};;
```

**Comment by jmmk** [comment]
It looks like I'm not handling the root variable correctly if it is a function (`function MediumButton(){}`) or an empty object (`var MediumButton = {};`). 

I recently added some tests, but it looks like I didn't write them correctly. I've fixed the tests and made sure I have two failing for these cases.

**Comment by martinklepsch** [comment]
@jmmk nice! 👍
